config/routes.rb
Rails.application.routes.draw do
  resources :genres

  get 'movies/filter/:scope' => "movies#index", as: :filtered_movies

  root "movies#index"
  resources :movies do
    resources :reviews
    resources :favorites
  end

  resources :users
  get 'signup' => 'users#new'

  resource :session
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_movies, through: :favorites, source: :movie

  validates :name, presence: true
  validates :email, presence: true,
                    format: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i,
                    uniqueness: { case_sensitive: false }

  def self.authenticate(email, password)
    user = User.find_by(email: email)
    user && user.authenticate(password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, exept: [:new, :create]
  before_action :require_correct_user, only: [:edit, :update, :destroy]

 def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
    @favorite_movies = @user.favorite_movies
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Thanks for signing up!"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: "Account successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session[:user_id] = nil
    redirect_to root_url, alert: "Account successfully deleted!"
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def require_correct_user
    @user = User.find(params[:id])
    redirect_to root_url unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render "shared/errors", object: @user %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :name %>
        <%= f.text_field :name, size: 40, autofocus: true %>
      </li>
      <li class="required">
        <%= f.label :email %>
        <%= f.email_field :email, size: 40 %>
      </li>
      <li class="required">
        <%= f.label :password %>
        <%= f.password_field :password, size: 40 %>
      </li>
      <li class="required">
        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation, size: 40 %>
      </li>
    </ol>
    <p>
      <% if @user.new_record? %>
        <%= f.submit "Create Account" %>
      <% else %>
        <%= f.submit "Update Account" %>
      <% end %>
    </p>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<header id="content-header">
  <h1>Edit Account</h1>
</header>

<%= render 'form' %>

app/views/users/index.html.erb
<header id="content-header">
  <h1><%= pluralize(@users.size, 'User') %></h1>
</header>

<ul id="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<header id="content-header">
  <h1>Sign Up</h1>
</header>

<%= render 'form' %>

app/views/users/show.html.erb
<% content_for(:title, @user.name) %>

<article id="user">
  <header>
    <h1><%= @user.name %></h1>
    <h2><%= mail_to(@user.email) %></h2>
  </header>

  <% if @reviews.any? %>
    <h3>Reviews</h3>
    <ol id="reviews">
     <% @reviews.each do |review| %>
       <li>
         <%= link_to review.movie.title, review.movie %>
         <span class="review"><%= pluralize(review.stars, 'star') %></span>
         <span class="date"><%= time_ago_in_words(review.created_at) %> ago</span>
         <p>
           &quot;<%= review.comment %>&quot;
         </p>
       </li>
     <% end %>
    </ol>
  <% end %>

  <% content_for :side do %>
    <% if @favorite_movies.any? %>
    <h3>Favorite Movies</h3>
    <ul>
      <% @favorite_movies.each do |movie| %>
        <li>
          <%= link_to movie.title, movie %>
        </li>
      <% end %>
    </ul>
    <% end %>
  <% end %>

  <footer>
    <nav>
      <% if current_user?(@user) %>
        <%= link_to 'Edit Account', edit_user_path(@user), class: 'button' %>
        <%= link_to 'Delete Account', @user,
                    method: :delete,
                    data: { confirm: 'Are you sure you want to permanently delete your account?' },
                    class: 'button' %>
      <% end %>
    </nav>
  </footer>
</article>