config/routes.rb
Rails.application.routes.draw do
  resources :genres

  get 'movies/filter/:scope' => "movies#index", as: :filtered_movies

  root "movies#index"
  resources :movies do
    resources :reviews
    resources :favorites
  end

  resources :users
  get 'signup' => 'users#new'

  resource :session
end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
  <p>
    Copyright &copy; 2019
    <%= link_to 'KuSeMi', 'https://gitlab.com/KuSeMi?nav_source=navbar' %>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
  <div id="masthead">
    <h1><%= link_to 'Flix', root_path %></h1>
    <nav>
      <p>
        <% if current_user %>
          <%= link_to current_user.name, current_user %>
          <%= link_to 'Sign Out', session_path, method: :delete, class: 'button' %>
        <% else %>
          <%= link_to 'Sign Up', signup_path, class: 'button' %>
          <%= link_to 'Sign In', new_session_path, class: 'button' %>
        <% end %>
      </p>
    </nav>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
  <nav>
    <ul>
      <li class="movies">
        <%= link_to 'Released', movies_path, class: 'button' %>
      </li>
      <li class="movies">
        <%= link_to 'Hits', filtered_movies_path(:hits), class: 'button' %>
      </li>
      <li class="movies">
        <%= link_to 'Flops', filtered_movies_path(:flops), class: 'button' %>
      </li>
      <li class="movies">
        <%= link_to 'Upcoming', filtered_movies_path(:upcoming), class: 'button' %>
      </li>
      <li class="movies">
        <%= link_to 'Recent', filtered_movies_path(:recent), class: 'button' %>
      </li>
      <% if current_user_admin? %>
        <li class="create-movie">
          <%= link_to 'Add New Movie', new_movie_path, class: 'button' %>
        </li>
      <% end %>
    </ul>
  </nav>
  <%= content_for(:side) %>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header" %>

    <div id="wrapper">

      <%= render "layouts/flashes" %>
      
      <div id="container">
        <section id="sidebar">
          <%= render "layouts/sidebar" %>
        </section>
        <section id="content">
          <%= yield %>
        </section>
      </div>

    </div>

    <%= render "layouts/footer" %>
  </body>
</html>